# Rasa configuration file.

recipe: default.v1

language: en

assistant_id: 20250531-104328-grizzled-vector

log_level: DEBUG


pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
    case_sensitive: false
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"
    trainable: true
    fine_tuning_epochs: 2
    learning_rate: 3e-5
    pooling: "mean"
    optimizer_name: "AdamW"
    layerwise_decay: 0.9
  - name: DIETClassifier
    batch_strategy: balanced
    hidden_layers_sizes:
      text: [128, 128] 
    dropout_rate: 0.5
    use_mc_dropout: true
    epochs: 80
    batch_size: 32
    early_stopping: true
    patience: 8
    tensorboard_log_directory: "./tb_logs2"
    tensorboard_log_level: "batch"
    random_seed: 42
    learning_rate: 0.0005
    optimizer_name: "Adam"
    l2_regularization: 0.15
    label_smoothing: 0.15
    entity_recognition: true
    loss_type: "cross_entropy"
    similarity_type: "inner"
    BILOU_flag: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

# Policy configuration
policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_handle_escalated_fallback"
    enable_fallback_prediction: true
  - name: MemoizationPolicy
  - name: TEDPolicy
    hidden_layers_sizes:
      text: [256, 128]
    epochs: 50
    return_diagnostic_data: true
    dropout_rate: 0.4
    learning_rate: 0.0003
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 60
    dropout_rate: 0.2
    learning_rate: 0.001
